### PR TITLE
Initial stab at a webhook receiver which just logs events

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

- [x] First stab at a github webhook receiver in Golang.
- [x] Takes a web hook HTTP request, returns OK (200) and logs the request
- Does not send any status to the pull request saying 'pending' (yet)
- [x] Build process to build a docker image with that go code
  - [x] in main branch build
  - [x] in pull request build
- Does not yet deploy the built image to the external repo.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by techcobweb** [comment]
@AaronJhaj Should I change the PR pipeline in the same way ?

**Comment by techcobweb** [comment]
Where is the code which deploys the built image to the external repository ?

How can that be tied into the building of the image ?

**Comment by techcobweb** [comment]
Is there an example of the build task which tells github the status of the build ?
I need to do something similar to tell the PR "pending..."

**Comment by AaronJhaj** [comment]
> @AaronJhaj Should I change the PR pipeline in the same way ?

Yes please. Also there should be a docker build task 'build-openapi-image' that has been recently added to the automation pipelines which I don't see here. I think a git pull is needed to make sure there will be no conflicts

**Comment by AaronJhaj** [comment]
> Where is the code which deploys the built image to the external repository ?
> 
> How can that be tied into the building of the image ?

We don't currently deploy the build artefacts of the automation repo if this is what you mean?

**Comment by techcobweb** [comment]
> Also there should be a docker build task 'build-openapi-image' that has been recently added to the automation pipelines which I don't see here. I think a git pull is needed to make sure there will be no conflicts
Not sure I believe you, as there are no merge conflicts.

**Comment by galasa-team** [comment]
Build successful

**Comment by AaronJhaj** [comment]
> > Also there should be a docker build task 'build-openapi-image' that has been recently added to the automation pipelines which I don't see here. I think a git pull is needed to make sure there will be no conflicts
> 
> Not sure I believe you, as there are no merge conflicts.

The code is up to date I didn't scroll down far enough but everything is there.

**Review by AaronJhaj — APPROVED** [review]

**Pull request merged**
