### PR TITLE
added local action

### PR DESCRIPTION
**Pull request by jaydee029**
Added custom local github action to setup maven gpg signing.

Sample usage

```
 - name: Setup GPG Secrets and custom settings.xml
    uses: ./.github/actions/maven-gpg-setup
    with:
       MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
       GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
       GPG_KEY_BASE64: ${{ secrets.GPG_KEY }}
```

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Review by jadecarino — APPROVED** [review]
Approved for building

**Review by jadecarino — APPROVED** [review]
Approved for building

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
