### PR TITLE
Fix runs prepare commands when adding internal-inttests to portfolio

### PR DESCRIPTION
**Pull request by eamansour**
## Why?
Related to changes in https://github.com/galasa-dev/automation/pull/617

`runs prepare` doesn't accept multiple `--stream` flags, so this PR adds a separate `runs prepare` step to append the tests in the `internal-inttests` stream to the regression test portfolio.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]
Good stuff approved!

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
