### PR TITLE
Replace helm test with validateeco and add cleanup to branch pipeline

### PR DESCRIPTION
**Pull request by eamansour**
For https://github.com/galasa-dev/projectmanagement/issues/1341

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Review by AaronJhaj — CHANGES_REQUESTED** [review]
Should line 54 be using $(params.imageTag)? is this what it means by galasaVersion and not 0.25.0 for example?

**Comment by eamansour** [comment]
> Should line 54 be using $(params.imageTag)? is this what it means by galasaVersion and not 0.25.0 for example?

Yep, `galasaVersion` corresponds to the `galasa-boot-embedded` image's tag (see https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/templates/api.yaml#L72 for an example). Since the pipeline uses harbor as the `galasaRegistry`, we can use `main` to grab the latest dev version of the `galasa-boot-embedded` image.

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
