### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jimbo4794dev**

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Review by Jimbo4794 — COMMENTED** [review]
Approved for building

**Review by Jimbo4794 — COMMENTED** [review]
Hello there

**Review by Jimbo4794 — COMMENTED** [review]
Approved for building

**Review by Jimbo4794 — COMMENTED** [review]
Approved for building

**Pull request closed without merging**
