### PR TITLE
mcobbett copyrighter tool

### PR DESCRIPTION
**Pull request by techcobweb**
- copyright tool runs over a folder
- Processes Go files also

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-automation-pr-270-5l7cl-r-45kcf for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by Akyiaa — APPROVED** [review]
looks good

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-automation-pr-270-5l7cl-r-vpzvs for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
