### PR TITLE
Update galasabld task

### PR DESCRIPTION
**Pull request by jadecarino**
Signed-off-by: Jade Carino <jade.carino@ibm.com>

### CODE REVIEW

**Comment by jadecarino** [comment]
To do 'galasabld github xxx' commands for the release, galasabld will need access to the githubcreds secret. This secret hasn't been set up yet on the galasa-build namespace so I have kept the volumeMount section commented out for now so this doesn't fail the pipelines. I will uncomment when I have set up the secret next week (need someone with access to galasa-tekton to help me). I have also added the tag parameter as for releases we might use a different tag, but have set the default to main. @AaronJhaj

**Comment by galasa-team** [comment]
Build successful

**Review by AaronJhaj — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
