### PR TITLE
Parameterise branch in build pipelines

### PR DESCRIPTION
**Pull request by eamansour**
For https://github.com/galasa-dev/projectmanagement/issues/1273

Main changes:
- Added `branch` and `refspec` parameters to all pipelines
- Renamed pipeline files from `build-main` to `build-branch`

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]

**Pull request merged**
