### PR TITLE
Iss1642 - Open JDK Image with IBM certs to reach new galasa bootstrap endpoint

### PR DESCRIPTION
**Pull request by jadecarino**
Move IBM certs into common location so not repeated
Create new Open JDK 11 image with the IBM certs installed 
Build this image in the automation pipeline

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-automation-pr-376-gdgrc for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by techcobweb — DISMISSED** [review]

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-automation-pr-376-77zlh for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-automation-pr-376-77zlh-r-rmnwc for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
