### PR TITLE
Resources for Simplatform application and Helm chart

### PR DESCRIPTION
**Pull request by jadecarino**
Signed-off-by: Jade Carino <jade.carino@ibm.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by jadecarino** [comment]
@hobbit1983 @Jimbo4794 Hi both, was just hoping to get your thoughts on the Simplatform application. This will now be on the external cluster pulling from the simplatform-amd64 image from harbor.galasa.dev.

It is however looking for the 'prod' version of this image, which I'm not sure if we still want to go with that convention.

Also I decided not to write the yaml for the 'Application' ( https://github.com/galasa-dev/simplatform/blob/main/argocd/applicationHelm/application.yaml ) as this can just be set up on ArgoCD so seemed a bit unnecessary.

**Comment by hobbit1983** [comment]
not sure I understand enough of your comment to be able to review.  Happy to let @Jimbo4794 review if he has the time.  Else I might need some pointers

**Review by techcobweb — APPROVED** [review]
Looks good to me I think.

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
