### PR TITLE
commented out snapshots for icr steps

### PR DESCRIPTION
**Pull request by AaronJhaj**

### CODE REVIEW

**Review by techcobweb — COMMENTED** [review]
Why do this ? Thought we needed to use ICR...

**Comment by AaronJhaj** [comment]
> Why do this ? Thought we needed to use ICR...

we were getting the NO_ERROR when dealing with the images from icr so hopefully can do these steps manually (the ones commented out). the rest can still be run as normal as they are in harbor which is working fine as far as i know

**Comment by techcobweb** [comment]
From aaron today:
> i commented out the snapshot-mvp and snapshot-isolated steps and i have asked will to do those manually. Then once they have been pushed we can apply these changes and run this pipeline and hopefully it will be fine then the release hopefully wont be blocked

**Comment by techcobweb** [comment]
approving on that basis.

**Pull request merged**
