### PR TITLE
Improving automation of updating cps props

### PR DESCRIPTION
**Pull request by Akyiaa**
Story: https://github.com/galasa-dev/projectmanagement/issues/1804
Improvement on previous pull request: https://github.com/galasa-dev/automation/pull/503
Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
